### ISSUE TITLE
RpcInvalidArgumentException: Bad account number

### ISSUE THREAD

**Issue by JgBr123** [koczadly/jNano#16]
```
public void receiveAll(int bananoAmountThreshold)
    {
        try
        {
            WorkDifficultyPolicy banano = NetworkConstants.BANANO.getWorkDifficulties();
            WorkGenerator workGenerator = new CPUWorkGenerator(banano);

            BlockProducer blockProducer = new StateBlockProducer
            (
                BlockProducerSpecification.builder()
                    .defaultRepresentative("ban_1ka1ium4pfue3uxtntqsrib8mumxgazsjf58gidh1xeo5te3whsq8z476goo")
                    .workGenerator(workGenerator) // Generate work on the node
                    .build()
            );

            LocalRpcWalletAccount account = new LocalRpcWalletAccount(privateKey, Banano.KaliumRPC, blockProducer);

            BigDecimal bigDecimal = new BigDecimal(bananoAmountThreshold*0.1).setScale(1,RoundingMode.DOWN);
            Bukkit.getLogger().warning(bigDecimal.toString());
            NanoAmount amount = NanoAmount.valueOfNano(bigDecimal);
            account.receiveAll(amount);
        }
        catch(WalletActionException e) { e.printStackTrace(); }
    }
```

It probably is because i'm trying to generate a banano block instead of a nano block, but i don't know what to change to make it work for banano (Except for the WorkDifficulty)

**Comment by koczadly** [comment]
Do you know which particular line is throwing the error? A full stack trace would also help.

--- 

As a side note, I'd heavily recommend against using floats/doubles for currency, as it's imprecise. You can use `NanoAmount.DenominationImpl` (I believe... it's undergone various revisions so may differ with the jnano version you're using) to define a Banano currency. Declare a static instance somewhere like so:
```java
public static final NanoAmount.Denomination UNIT_BAN = new NanoAmount.DenominationImpl("Banano", 29);```

Then just use `NanoAmount.valueOf(yourBanValue, UNIT_BAN);` or whatever.

**Comment by JgBr123** [comment]
```
[20:09:22 WARN]: uk.oczadly.karl.jnano.rpc.util.wallet.WalletActionException: Failed to retrieve pending blocks.
[20:09:22 WARN]:        at bananobank-1.0.jar//uk.oczadly.karl.jnano.rpc.util.wallet.LocalRpcWalletAccount.receiveBatch(LocalRpcWalletAccount.java:323)
[20:09:22 WARN]:        at bananobank-1.0.jar//uk.oczadly.karl.jnano.rpc.util.wallet.LocalRpcWalletAccount.receiveAll(LocalRpcWalletAccount.java:372)
[20:09:22 WARN]:        at bananobank-1.0.jar//jgbr123.bananobank.methods.BananoWallet.receiveAll(BananoWallet.java:99)
[20:09:22 WARN]:        at bananobank-1.0.jar//jgbr123.bananobank.commands.BananoCommand.onCommand(BananoCommand.java:53)
[20:09:22 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[20:09:22 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[20:09:22 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905)
[20:09:22 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2306)
[20:09:22 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2117)
[20:09:22 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2098)
[20:09:22 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[20:09:22 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[20:09:22 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[20:09:22 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:09:22 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[20:09:22 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[20:09:22 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1399)
[20:09:22 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[20:09:22 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[20:09:22 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1376)
[20:09:22 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1369)
[20:09:22 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bo(IAsyncTaskHandler.java:114)
[20:09:22 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1503)
[20:09:22 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1225)
[20:09:22 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[20:09:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[20:09:22 WARN]: Caused by: uk.oczadly.karl.jnano.rpc.exception.RpcInvalidArgumentException: Bad account number.
[20:09:22 WARN]:        at bananobank-1.0.jar//uk.oczadly.karl.jnano.rpc.JsonResponseDeserializer.parseErrorMessage(JsonResponseDeserializer.java:160)
[20:09:22 WARN]:        at bananobank-1.0.jar//uk.oczadly.karl.jnano.rpc.JsonResponseDeserializer.parseException(JsonResponseDeserializer.java:108)
[20:09:22 WARN]:        at bananobank-1.0.jar//uk.oczadly.karl.jnano.rpc.JsonResponseDeserializer.deserialize(JsonResponseDeserializer.java:60)
[20:09:22 WARN]:        at bananobank-1.0.jar//uk.oczadly.karl.jnano.rpc.RpcQueryNode.processRequestRaw(RpcQueryNode.java:332)
[20:09:22 WARN]:        at bananobank-1.0.jar//uk.oczadly.karl.jnano.rpc.RpcQueryNode.processRequest(RpcQueryNode.java:209)
[20:09:22 WARN]:        at bananobank-1.0.jar//uk.oczadly.karl.jnano.rpc.RpcQueryNode.processRequest(RpcQueryNode.java:180)
[20:09:22 WARN]:        at bananobank-1.0.jar//uk.oczadly.karl.jnano.rpc.util.wallet.LocalRpcWalletAccount.receiveBatch(LocalRpcWalletAccount.java:320)
[20:09:22 WARN]:        ... 25 more
```

**Comment by JgBr123** [comment]
I'm using this at a minecraft plugin

**Comment by koczadly** [comment]
I'm not entirely sure what the issue is. Try one thing, add `.addressPrefix("ban")` to the `BlockProducerSpecification` instance you're using and see if that fixes it. I haven't tested most of the functions with Banano unfortunately.

**Comment by koczadly** [comment]
Also, as another note... I'm aware this may be in early development stage, but if possible you should try to re-use `LocalRpcWalletAccount` instances as they cache account state information. Additionally, you can run into problems if you have 2 separate instances operating on the same account, as Nano (and Banano) does not allow for concurrent account access. If you're handling multiple accounts, the recommended approach is to store them in a map.

**Comment by JgBr123** [comment]
Thanks so much!  `.addressPrefix("ban")` fixed the problem.
Also thanks for the tip for using `NanoAmount.valueOf(yourBanValue, UNIT_BAN)`, i didn't know this was possible.
And about the LocalRpcWalletAccount instances, i am just testing how the PoW works, don't worry. I will only have one instance per account in the finished stage.
