### ISSUE TITLE
RPC Exception: Cancelled

### ISSUE THREAD

**Issue by letskingit** [koczadly/jNano#5]
I get this error every now and again when processing a request.

The request is to generate work. What causes it?

Thanks,

Letskingit

**Comment by koczadly** [comment]
Hey, could you post a snippet of code or the exception message/type which is generated? Thanks

**Comment by koczadly** [comment]
This would typically happen if you cancelled a work generation request before it was completed using `work_cancel`. If you aren't doing this, then it's likely a bug in the actual Nano node's handling of work generation. Alternatively, if you're using a custom third-party provider they may timeout work requests.

It would be helpful to know which version of jNano you're using, and how you're constructing the `work_generate` requests, but I'm not too certain on what else could cause this.

**Comment by letskingit** [comment]
> Hey, could you post a snippet of code or the exception message/type which is generated? Thanks

uk.oczadly.karl.jnano.rpc.exception.RpcException: Cancelled
	at uk.oczadly.karl.jnano.rpc.RpcQueryNode.parseException(RpcQueryNode.java:328)
	at uk.oczadly.karl.jnano.rpc.RpcQueryNode.deserializeResponseFromJSON(RpcQueryNode.java:286)
	at uk.oczadly.karl.jnano.rpc.RpcQueryNode.processRequest(RpcQueryNode.java:173)
	at uk.oczadly.karl.jnano.rpc.RpcQueryNode.processRequest(RpcQueryNode.java:151)
	at nanobets.Tools.getWorkSolution(Tools.java:400)
	at nanobets.Main$1.run(Main.java:90)
	at nanobets.UserThread.run(UserThread.java:72)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:851)

**Comment by letskingit** [comment]
> This would typically happen if you cancelled a work generation request before it was completed using `work_cancel`. If you aren't doing this, then it's likely a bug in the actual Nano node's handling of work generation. Alternatively, if you're using a custom third-party provider they may timeout work requests.
> 
> It would be helpful to know which version of jNano you're using, and how you're constructing the `work_generate` requests, but I'm not too certain on what else could cause this.

I'm using JNano 2.0.1 V20 
Not using work cancel and not using any third party service.

I did update my node a couple days ago to V21.2 and this is what I assume has started the issues.

Will upgrade to the latest version of Jnano.
