### ISSUE TITLE
uk.oczadly.karl.jnano.model.block.BlockDeserializer$BlockParseException: Could not parse block (malformed json?).

### ISSUE THREAD

**Issue by letskingit** [koczadly/jNano#9]
uk.oczadly.karl.jnano.model.block.BlockDeserializer$BlockParseException: Could not parse block (malformed json?).
        at uk.oczadly.karl.jnano.model.block.BlockDeserializer.deserialize(BlockDeserializer.java:105)
        at uk.oczadly.karl.jnano.model.block.BlockDeserializer$JsonAdapter.deserialize(BlockDeserializer.java:174)
        at uk.oczadly.karl.jnano.model.block.BlockDeserializer$JsonAdapter.deserialize(BlockDeserializer.java:144)
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:1003)
        at com.google.gson.Gson.fromJson(Gson.java:975)
        at uk.oczadly.karl.jnano.callback.BlockCallbackServer$HttpCallbackProcessor.onRequest(BlockCallbackServer.java:129)
        at uk.oczadly.karl.jnano.callback.httpserver.HttpRequestHandler.run(HttpRequestHandler.java:67)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:851)
Caused by: java.lang.IllegalArgumentException: Subtype cannot be null.
        at uk.oczadly.karl.jnano.model.block.StateBlock.<init>(StateBlock.java:154)
        at uk.oczadly.karl.jnano.model.block.StateBlock.lambda$static$0(StateBlock.java:40)
        at uk.oczadly.karl.jnano.model.block.StateBlock$$Lambda$108/0000000000000000.apply(Unknown Source)
        at uk.oczadly.karl.jnano.model.block.BlockDeserializer.deserialize(BlockDeserializer.java:103)

Using version: 2.8.0-V21.2
Using the latest nano node version as well. 

Not really sure what causes this error and need some guidance on this.

Thanks!

**Comment by koczadly** [comment]
Hey, thanks for bringing this to my attention. 

How often do you notice this error? This looks like it's going to be very difficult to debug if it's a rare occurrence, but it seems the node is giving the callback server incomplete state blocks for whatever reason. Do you perhaps know any more about which block caused it, or do you only have the stacktrace log?

As a side note, it might be worth upgrading your code to use the websocket API instead of the callback server, it's typically more stable and reliable.

**Comment by letskingit** [comment]
Thanks for the response.

This error occurs every 5-10 seconds in the logs. I don't know which block has caused it nor do I understand much about the error and how is occurs.

For processing deposits, I just use a database to store nano addresses and check periodically if any any of them have a positive balance. This method has been very reliable and less error prone than checking for deposits in real time.

**Comment by koczadly** [comment]
Sorry mate, still looking into this. Had syncing issues on my local test node.

**Comment by koczadly** [comment]
@letskingit Version `2.8.1-V21.2` has been pushed and should fix this. Let me know how it goes.

**Comment by letskingit** [comment]
Alright, updated and the error is gone, thank you! Thanks for the advice as well, will switch to WebSocket soon if it's easy to do so.
